# Generated by Django 4.0.5 on 2022-06-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сareers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('coordinates', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Flight', models.DateTimeField(null=True)),
                ('weight', models.FloatField()),
                ('coordinates', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constr.сareers', verbose_name='career')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constr.trucks', verbose_name='truck')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constr.warehouses', verbose_name='warehouse')),
            ],
        ),
    ]
