# Generated by Django 4.0.5 on 2022-06-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constr', '0002_alter_flights_options_alter_trucks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='career_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constr.сareers', verbose_name='Карьер'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Рейс завершен'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Координаты выгрузки'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='date_Flight',
            field=models.DateTimeField(verbose_name='Дата рейса'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='truck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constr.trucks', verbose_name='Самосвал'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constr.warehouses', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
